Update Login page.
NativeScript/nativescript-page-templates-ng pull request #5
Opened 2017-07-21 12:28 UTC by ADjenkov

Remove nativescript-facebook plugin
Make SASS ready

2017-07-24 08:25 UTC, lini approved these changes

2017-07-24 15:34 UTC, manoldonev requested changes
tslint errors -- maybe add comments in the empty blocks?

```
D:\GitHub\nativescript-page-templates-ng\login [djenkov/update-login ≡ +1 ~0 -0 !]> npm run lint

> @ lint D:\GitHub\nativescript-page-templates-ng\login
> tslint "app/**/*.ts"


ERROR: app/login/login.component.ts[12, 19]: block is empty
ERROR: app/login/login.component.ts[15, 22]: block is empty
ERROR: app/login/login.component.ts[18, 32]: block is empty
ERROR: app/login/login.component.ts[21, 30]: block is empty
ERROR: app/login/login.component.ts[24, 25]: block is empty
ERROR: app/login/login.component.ts[27, 27]: block is empty
```

2017-07-24 15:41 UTC, manoldonev commented
Btw, on the wireframes http://ux.telerik.com/wireframes/UX%20Patterns/#p=login&g=1 there is additional checkbox "Show password"

2017-08-01 08:20 UTC, manoldonev approved these changes

2017-08-01 08:21 UTC, merged